### ISSUE TITLE
Edit router problems

### ISSUE THREAD

**Issue by amorino** [knowbody/redux-react-router-example-app#11]
Currently, accessing to /post/id/edit directly from the browser doesn't load anything. This will be solved using `<script src="/static/bundle.js"></script>` instead of `<script src="./static/bundle.js"></script>` index. Fixing this, the only parameter the Draft component will load is the image route.

**Comment by knowbody** [comment]
@Amorino wanna send a PR for that?

**Comment by amorino** [comment]
I will try. I'm not familiar with the code, maybe you can fix it quicker. I think the problem is the initialState of the Draft component.

**Comment by knowbody** [comment]
I think the code itself is fine. the issue is the `.` in the `<script src="">`

the PR from #10 should fix that

**Comment by amorino** [comment]
Yeah, what I'm referring is: 

If you enter the edit (eg. localhost:3000/post/1/edit) Route from browser, the state for the Draft component is empty (new Post).

**Comment by knowbody** [comment]
ok thanks! I'll look into it and I get back to you
