### ISSUE TITLE
Shall we put this into the README?

### ISSUE THREAD

**Issue by tanertopal** [knowbody/redux-react-router-example-app#15]
I was a bit confused about the structural change of the redux components so after a bit reactiflux I got this link: https://github.com/erikras/ducks-modular-redux

I think we should put something like

---
### Redux

The redux structure follows the [ducks modular redux proposal](https://github.com/erikras/ducks-modular-redux)

---

I think it would help understanding the WHY? What do you think?

**Comment by knowbody** [comment]
@tanertopal yeah definitely, you know I'm open to the changes which make stuff easier to understand :)

**Comment by tanertopal** [comment]
kk I'll send you a PR

**Comment by knowbody** [comment]
also with README updates, feel free to just push to master, I think you have the access.

**Comment by tanertopal** [comment]
yup will do
