### ISSUE TITLE
npm start warning

### ISSUE THREAD

**Issue by zanjs** [knowbody/redux-react-router-example-app#18]
Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

**Comment by knowbody** [comment]
I don't use `findDOMNode` anywhere, mind pointing out where is this error coming from?

**Comment by tanertopal** [comment]
@zanjs If you use it make sure to use this package https://www.npmjs.com/package/react-dom
Facebook decided to extract the DOM renderer into an extra npm library so it is just another renderer for react.

**Comment by zanjs** [comment]
Thank you very much!

**Comment by knowbody** [comment]
@tanertopal thank you :)
