### ISSUE TITLE
react-transform-catch-errors

### ISSUE THREAD

**Issue by ghost** [knowbody/redux-react-router-example-app#23]
hello thanks for this great project setup
## i'm getting following Error:

imports[1] for react-transform-catch-errors does not look like a React component.

**Comment by maxsbelt** [comment]
There is a problem with dependency package `redbox-react`.
To fix that problem you need to specify `1.2.6` version of the package `redbox-react` instead of '^1.1.1' in your `package.json` file.
Solution was found in [stackoverflow](http://stackoverflow.com/a/37950114).

**Comment by knowbody** [comment]
@maxsbelt thank you for pointing out the solution
